swagger: "2.0"
info:
  version: "1.0.0"
  title: "User Spec"
  termsOfService: "http://swagger.io/terms/"
host: "alnitech.lms.io"
basePath: "/v2"
schemes:
  - "https"
  - "http"

paths:
  /user/all:
    get:
      tags:
        - "user"
      summary: "Get all users"
      description: ""
      operationId: "getAllUsers"
      produces:
        - "application/xml"
        - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
#securityDefinitions:
#  petstore_auth:
#    type: "oauth2"
#    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#    flow: "implicit"
#    scopes:
#      write:pets: "modify pets in your account"
#      read:pets: "read your pets"
#  api_key:
#    type: "apiKey"
#    name: "api_key"
#    in: "header"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      userRole:
        type: "integer"
        format: "int32"
        description: "User Role"
    xml:
      name: "User"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
